import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/header";
import { getBaseURL } from "@/lib/get-base-url";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const senobiGothic = localFont({
  src: [
    {
      path: "./fonts/Senobi-Gothic-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Senobi-Gothic-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Senobi-Gothic-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-senobi-gothic",
  display: "swap",
});

const academy = localFont({
  src: [
    {
      path: "./fonts/Academy.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/AcademyFilled3D.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-academy",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: "%s | IK Alumni Club",
    default: "IK Alumni Club",
  },
  metadataBase: new URL(getBaseURL()),
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${senobiGothic.variable} ${academy.variable} antialiased`}
      >
        <NuqsAdapter>
          <Header />
          {children}
          <Toaster />
        </NuqsAdapter>
      </body>
    </html>
  );
}
